baseURL: "https://callmemaru.com/"
defaultContentLanguage: ko
title: "Call Me Maru"
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-113083768-3
permalinks:
  posts: /:section/:filename/

languages:
  ko:
    languageName: "Korea"
    weight: 1
    menu:
      main:
        - name: About
          url: about/
          weight: 5
        - name: Tags
          url: tags/
          weight: 10

minify:
  disableXML: true
  minifyOutput: true

params:
  env: development # to enable google analytics, opengraph, twitter-cards and schema.
  title: Call me maru
  description: "Maru's dev blog"
  author: Maru

  images:
    - og_image.png

  ShowReadingTime: true
  ShowShareButtons: true
  comments: false
  defaultTheme: auto
  disableThemeToggle: false
  disableSpecial1stPost: false

  assets:
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "/favicon-32x32.png"
    safari_pinned_tab: "/favicon-32x32.png"

  label:
    text: "Call Me Maru"
    # icon: /apple-touch-icon.png
    # iconHeight: 35

  # home-info mode
  homeInfoParams:
    Title: "안녕하세요 \U0001F44B"
    Content: 마루라고 불러주세요!

  socialIcons:
    - name: github
      url: "https://github.com/gmlwo530/"
    - name: email
      url: "mailto:gmlwo530@gmail.com"
    - name: instagram
      url: "https://www.instagram.com/shaq_choi/"
    - name: linkedin
      url: "https://www.linkedin.com/in/hee-jae-5771bb188/"
    - name: RsS
      url: "index.xml"

  # analytics:
  #   google:
  #     SiteVerificationTag: "XYZabc"
